# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KronaxisRouter < Formula
  desc "Intelligent LLM proxy with cost-optimised routing"
  homepage "https://github.com/Kronaxis/kronaxis-router"
  version "1.1.0"
  license "Apache-2.0"

  depends_on "go" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Kronaxis/kronaxis-router/releases/download/v1.1.0/kronaxis-router_1.1.0_darwin_amd64.tar.gz"
      sha256 "19e89d48378a8163efdd6b4d7aad4d8af17adcae8d1d14d7ea0300aa7ce46020"

      define_method(:install) do
        bin.install "kronaxis-router"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Kronaxis/kronaxis-router/releases/download/v1.1.0/kronaxis-router_1.1.0_darwin_arm64.tar.gz"
      sha256 "cf9d73fcf2bd09f808ca9fdd0905054f14648fce7b3aa428214a78d7338722dd"

      define_method(:install) do
        bin.install "kronaxis-router"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Kronaxis/kronaxis-router/releases/download/v1.1.0/kronaxis-router_1.1.0_linux_amd64.tar.gz"
      sha256 "0f0d1d9525fdc9168432ef7124051afd8f6a6ab0414f48a030b84c042d5c50d4"
      define_method(:install) do
        bin.install "kronaxis-router"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Kronaxis/kronaxis-router/releases/download/v1.1.0/kronaxis-router_1.1.0_linux_arm64.tar.gz"
      sha256 "5a62932e4221e72b957a090fc1a1b93658a0952d1c5946435fb7f26bbbd33623"
      define_method(:install) do
        bin.install "kronaxis-router"
      end
    end
  end

  test do
    system "#{bin}/kronaxis-router", "version"
  end
end
