# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KronaxisRouter < Formula
  desc "Intelligent LLM proxy with cost-optimised routing"
  homepage "https://github.com/Kronaxis/kronaxis-router"
  version "1.1.0"
  license "Apache-2.0"

  depends_on "go" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Kronaxis/kronaxis-router/releases/download/v1.1.0/kronaxis-router_1.1.0_darwin_amd64.tar.gz"
      sha256 "1a9caa29d11a5cd12bdef3ef6b2ab42ab0336e6c1c4cc1c920319e71ce071228"

      define_method(:install) do
        bin.install "kronaxis-router"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Kronaxis/kronaxis-router/releases/download/v1.1.0/kronaxis-router_1.1.0_darwin_arm64.tar.gz"
      sha256 "dcdddedec224a42a3614e939554e0dafc4fb4f5e4efecc9953b51eb4ae3688dc"

      define_method(:install) do
        bin.install "kronaxis-router"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Kronaxis/kronaxis-router/releases/download/v1.1.0/kronaxis-router_1.1.0_linux_amd64.tar.gz"
      sha256 "35cac164d3447cbdccd1df4d8730a335cf341887b0f40d138a388225d0bcf14d"
      define_method(:install) do
        bin.install "kronaxis-router"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Kronaxis/kronaxis-router/releases/download/v1.1.0/kronaxis-router_1.1.0_linux_arm64.tar.gz"
      sha256 "215d366370be693990fa525c34176cb879bf06d1d437d7e10c352175b5ad3bd9"
      define_method(:install) do
        bin.install "kronaxis-router"
      end
    end
  end

  test do
    system "#{bin}/kronaxis-router", "version"
  end
end
