# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KronaxisRouter < Formula
  desc "Intelligent LLM proxy with cost-optimised routing"
  homepage "https://github.com/Kronaxis/kronaxis-router"
  version "1.1.0"
  license "Apache-2.0"

  depends_on "go" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Kronaxis/kronaxis-router/releases/download/v1.1.0/kronaxis-router_1.1.0_darwin_amd64.tar.gz"
      sha256 "eca2d1647e7c7b243b7320b72fc913877d170899051c200427ce170adbdfbec0"

      define_method(:install) do
        bin.install "kronaxis-router"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Kronaxis/kronaxis-router/releases/download/v1.1.0/kronaxis-router_1.1.0_darwin_arm64.tar.gz"
      sha256 "7b213bc68b55d55e7c00195585fa4173b7177c5d162634c8e19f5a8f18d8d101"

      define_method(:install) do
        bin.install "kronaxis-router"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Kronaxis/kronaxis-router/releases/download/v1.1.0/kronaxis-router_1.1.0_linux_amd64.tar.gz"
      sha256 "3e93333432907a5bfc006584e61d4552baf6dc9573e4eec14d9a20a7d197b7f0"
      define_method(:install) do
        bin.install "kronaxis-router"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Kronaxis/kronaxis-router/releases/download/v1.1.0/kronaxis-router_1.1.0_linux_arm64.tar.gz"
      sha256 "502f7618fed0f6dc1f35ced9ab55f85869bbfcdd8923ae7853596d1b24b1d270"
      define_method(:install) do
        bin.install "kronaxis-router"
      end
    end
  end

  test do
    system "#{bin}/kronaxis-router", "version"
  end
end
